name: Build and Deploy CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js 12
          uses: actions/setup-node@v2
          with:
              node-version: '12.x'
        - run: npm install -g firebase-tools yarn
        - run: yarn install
        - run: yarn build
          env:
              GATSBY_GITHUB_API_TOKEN: ${{ secrets.GATSBY_GITHUB_API_TOKEN }}
              GATSBY_GOOGLE_ANALYTICS: ${{ secrets.GATSBY_GOOGLE_ANALYTICS }}
        - run: aws s3 sync public/ s3://linkletter.dev --delete
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: "us-east-1"
