name: Build and Deploy CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js 12
          uses: actions/setup-node@v2
          with:
              node-version: '12.x'
        - run: npm install -g firebase-tools yarn
        - run: yarn install
        - run: yarn build
          env:
              GATSBY_GITHUB_API_TOKEN: ${{ secrets.GATSBY_GITHUB_API_TOKEN }}
              GATSBY_GOOGLE_ANALYTICS: ${{ secrets.GATSBY_GOOGLE_ANALYTICS }}
        - run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
          env: 
              CI: true
